<?xml version="1.0" encoding="utf-8"?><Database Name="PeopleData" Class="PeopleDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Dev\FortyDigits.Templating\FortyDigits.Templating.Tests\App_Data\PeopleData.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="FortyDigits.Templating.Tests.Properties.Settings" SettingsPropertyName="PeopleDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.People" Member="Peoples">
    <Type Name="People">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Music" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Sport" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>